=== anna-lipatova/Data-Formats-projects/HW3/xml/schemas/schema-1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace"
               schemaLocation="https://www.w3.org/2009/01/xml.xsd"/>


    <xs:complexType name="LangString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!-- Type Employee-->
    <xs:simpleType name="TypeEmployeeId">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>
    <xs:complexType name="TypeEmployeeIds">
        <xs:sequence>
            <xs:element name="EmployeeId" type="TypeEmployeeId" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TypeEmployee">
        <xs:sequence>
            <!-- Properties -->
            <xs:element name="Given_name" type="LangString"/>
            <xs:element name="Family_name" type="LangString"/>
        </xs:sequence>
        <xs:attribute name="EmployeeId" type="TypeEmployeeId" use="required"/>
    </xs:complexType>
    <xs:complexType name="TypeEmployees">
        <xs:sequence>
            <xs:element name="Employee" type="TypeEmployee" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Type Cash Register-->
    <xs:simpleType name="TypeCashRegisterId">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>
    <xs:complexType name="TypeCashRegisterIds">
        <xs:sequence>
            <xs:element name="CashregisterId" type="TypeCashRegisterId" minOccurs="1"
                        maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TypeCashRegister">
        <xs:sequence>
            <!-- Properties -->
            <xs:element name="Number" type="xs:integer"/>
            <xs:element name="Is_self_checkout" type="xs:boolean"/>
            <!-- Relation refs-->
            <xs:element name="Employee" type="TypeEmployee"/>
        </xs:sequence>
        <xs:attribute name="CashRegisterId" type="TypeCashRegisterId" use="required"/>
    </xs:complexType>
    <xs:complexType name="TypeCashRegisters">
        <xs:sequence>
            <xs:element name="CashRegister" type="TypeCashRegister" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


    <!-- Type Customer-->
    <xs:simpleType name="TypeCustomerId">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>
    <xs:complexType name="TypeCustomerIds">
        <xs:sequence>
            <xs:element name="CustomerId" type="TypeCustomerId" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="TypeCustomer">
        <xs:sequence>
            <!-- Properties -->
            <xs:element name="Given_name" type="LangString"/>
            <xs:element name="Family_name" type="LangString"/>
            <xs:element name="Birth_date" type="xs:date"/>
            <xs:element name="Phone_number" type="LangString"/>
        </xs:sequence>
        <xs:attribute name="CustomerId" type="TypeCustomerId" use="required"/>
    </xs:complexType>
    <xs:complexType name="TypeCustomers">
        <xs:sequence>
            <xs:element name="Customer" type="TypeCustomer" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Type Address-->
    <xs:simpleType name="TypeAddressId">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>
    <xs:complexType name="TypeAddress">
        <xs:sequence>
            <!-- Properties -->
            <xs:element name="City" type="LangString"/>
            <xs:element name="Street" type="LangString"/>
            <xs:element name="Zip_code" type="LangString"/>
        </xs:sequence>
        <xs:attribute name="AddressId" type="TypeAddressId" use="required"/>
    </xs:complexType>

    <!--Type Store Branch-->
    <xs:simpleType name="TypeStoreBranchId">
        <xs:restriction base="xs:anyURI"/>
    </xs:simpleType>
    <xs:complexType name="TypeStoreBranch">
        <xs:sequence>
            <!-- Properties-->
            <xs:element name="Name" type="LangString"/>
            <xs:element name="has_warehouse" type="xs:boolean"/>
            <!-- Relations direct -->
            <xs:element name="Customers" type="TypeCustomers"/>
            <xs:element name="Employees" type="TypeEmployees"/>
            <xs:element name="CashRegisters" type="TypeCashRegisters"/>
            <!-- Relation refs-->
            <xs:element name="Address" type="TypeAddress"/>
        </xs:sequence>
        <xs:attribute name="StoreBranchId" type="TypeStoreBranchId" use="required"/>
    </xs:complexType>
    <xs:complexType name="TypeStoreBranches">
        <xs:sequence>
            <xs:element name="StoreBranch" type="TypeStoreBranch" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Root -->
    <xs:element name="StoreBranches" type="TypeStoreBranches"/>
</xs:schema>

=== anna-lipatova/Data-Formats-projects/HW3/xml/data/data-1.xml
<?xml version="1.0" encoding="utf-8"?>
<StoreBranches xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../schemas/schema-1.xsd">
    <StoreBranch id="http://example.org/store/StoreBranch1">
        <Name xml:lang="cs">Albert Liberec, Žižkova</Name>
        <has_warehouse>false</has_warehouse>
        <Customers>
            <Customer customerId="http://example.org/customer/Petra-Mrkvickova">
                <Given_name>Petra</Given_name>
                <Family_name>Mrkvickova</Family_name>
                <Birth_date>2002-02-02</Birth_date>
                <Phone_number>tel:+420123321231</Phone_number>
            </Customer>
        </Customers>
        <Addresses>
            <Address>
                <City xml:lang="cs">Liberec</City>
                <Street xml:lang="cs">Prokopova, 261</Street>
                <Zip_code>10400</Zip_code>
            </Address>
        </Addresses>
        <CashRegisters>
            <CashRegister registerId="http://example.org/register/1">
                <Number>1</Number>
                <Is_self_checkout>true</Is_self_checkout>
                <Employees>
                    <Employee employeeId="http://example.org/person/Marie-Krasna">
                        <Given_name>Marie</Given_name>
                        <Family_name>Krásná</Family_name>
                    </Employee>
                </Employees>
            </CashRegister>
        </CashRegisters>
        <Employees>
            <Employee employeeId="http://example.org/person/Marie-Krasna">
                <Given_name>Marie</Given_name>
                <Family_name>Krásná</Family_name>
            </Employee>
        </Employees>
    </StoreBranch>

    <StoreBranch id="http://example.org/store/StoreBranch2">
        <Name xml:lang="cs">Albert Olomouc</Name>
        <has_warehouse>false</has_warehouse>
        <Customers>
            <Customer customerId="http://example.org/customer/Marek-Velky">
                <Given_name>Marek</Given_name>
                <Family_name>Veľký</Family_name>
                <Birth_date>2001-01-01</Birth_date>
                <Phone_number>tel:+420777777777</Phone_number>
            </Customer>
        </Customers>
        <Addresses>
            <Address>
                <City xml:lang="cs">Olomouc</City>
                <Street xml:lang="cs">Polska, 1</Street>
                <Zip_code>77900</Zip_code>
            </Address>
        </Addresses>
        <CashRegisters>
            <CashRegister registerId="http://example.org/register/2">
                <Number>2</Number>
                <Is_self_checkout>false</Is_self_checkout>
                <Employees>
                    <Employee employeeId="http://example.org/person/Janko-Mrkvicka">
                        <Given_name>Janko</Given_name>
                        <Family_name>Mrkvicka</Family_name>
                    </Employee>
                </Employees>
            </CashRegister>
        </CashRegisters>
        <Employees>
            <Employee employeeId="http://example.org/person/Janko-Mrkvicka">
                <Given_name>Janko</Given_name>
                <Family_name>Mrkvicka</Family_name>
            </Employee>
        </Employees>
    </StoreBranch>

    <StoreBranch id="http://example.org/store/StoreBranch3">
        <Name xml:lang="cs">Albert Brno</Name>
        <has_warehouse>true</has_warehouse>
        <Customers>
            <Customer customerId="http://example.org/customer/Janka-Cibulkova">
                <Given_name>Janka</Given_name>
                <Family_name>Cibulkova</Family_name>
                <Birth_date>2003-03-03</Birth_date>
                <Phone_number>tel:+420666666666</Phone_number>
            </Customer>
        </Customers>
        <Addresses>
            <Address>
                <City xml:lang="cs">Brno</City>
                <Street xml:lang="cs">Nádražní, 2</Street>
                <Zip_code>60200</Zip_code>
            </Address>
        </Addresses>
        <CashRegisters>
            <CashRegister registerId="http://example.org/register/3">
                <Number>3</Number>
                <Is_self_checkout>true</Is_self_checkout>
                <Employees>
                    <Employee employeeId="http://example.org/person/Peter-Cibulka">
                        <Given_name>Peter</Given_name>
                        <Family_name>Cibulka</Family_name>
                    </Employee>
                </Employees>
            </CashRegister>
        </CashRegisters>
        <Employees>
            <Employee employeeId="http://example.org/person/Peter-Cibulka">
                <Given_name>Peter</Given_name>
                <Family_name>Cibulka</Family_name>
            </Employee>
        </Employees>
    </StoreBranch>
</StoreBranches>
